### PR TITLE
Add route to view all orders

### LINKED ISSUE #126: Create order history page
Create a new page where all past orders are listed

### PR DESCRIPTION
**Pull request by Jan-PieterBaert**
This implements and closes #126

### CODE REVIEW

**Comment by redfast00** [comment]
@Jan-PieterBaert @SchrodingersCat00 What's the usecase of this feature? This will be a pretty heavy page to load, and will not be in a useful format (HTML instead of something like JSON).

**Comment by wschella** [comment]
@redfast00 sometimes you need look for past orders to fix some personal financing

**Comment by mcbloch** [comment]
We can support this for admins or for showing your own orders. We do not want to publicly list all orders as we are even working on anonymizing all of them with unique links.

**Comment by Jan-PieterBaert** [comment]
> We can support this for admins or for showing your own orders. We do not want to publicly list all orders as we are even working on anonymizing all of them with unique links.

In that case I'll close this issue and you might consider changing #126 as well

**Comment by mcbloch** [comment]
> In that case I'll close this issue and you might consider changing https://github.com/ZeusWPI/Haldis/issues/126 as well

Good catch

**Pull request closed without merging**
