### PR TITLE
Remove Google Analytics

### PR DESCRIPTION
**Pull request by redfast00**

### CODE REVIEW

**Comment by mcbloch** [comment]
Is this line part of analytics?
`{% import "bootstrap/google.html" as google %}`

**Comment by mcbloch** [comment]
I was talking about this with @tl3ilaxu yesterday, we could use a small oss library to get some cool stats about the activity of the site that isn't sent to google or maybe use an access.log analyzer...?

**Comment by redfast00** [comment]
@mcbloch it is

Or we could do the same thing we're doing with the Zeussite.

**Comment by mcbloch** [comment]
Yes, I like good, I heard of the fathom lib before but didn't had the time then to look into it.
I'll make it a new issue to implement it into haldis.

**Pull request merged**
